export const SET_CURRENT_TIME = "SET_CURRENT_TIME";
export const SET_HEADER_TEXT = "SET_HEADER_TEXT";
export const SET_START_TIME = "SET_START_TIME";
export const SET_CURRENT_PHRASE_ID = "SET_CURRENT_PHRASE_ID";
export const SET_SCORE_TOGGLES = "SET_SCORE_TOGGLES";
export const SET_SIDEBAR_STATE = "SET_SIDEBAR_STATE";
export const SET_NARRATIVE_TAB = "SET_NARRATIVE_TAB";
